config/routes.rb
Rails.application.routes.draw do

	root to: 'gossips#index'
	get 'static_pages/team', to: 'static_pages#team', as: 'team'
	get 'static_pages/contact', to: 'static_pages#contact', as: 'contact'
	get 'static_pages/:first_name', to: 'static_pages#welcome', as: 'secret_page'

	resources :gossips do
		resources :comments
	end
	resources :users
	resources :cities, only: [:show]
	resources :sessions, only: [:new, :create, :destroy]
	resources :likes, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users

	validates :name,
    	presence: true
    validates :zip_code,
    	presence: true,
    	uniqueness: true,
    	format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Reneignez un code postal valide." }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :potin
  belongs_to :user
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
     belongs_to :potin
     belongs_to :user
end

app/models/potin.rb
class Potin < ApplicationRecord
	belongs_to :user
        has_many :taggers
        has_many :tags, through: :taggers
        has_many :comments
	has_many :likes

    validates :title,
    	presence: true,
    	length: { in: 3..14, message: "Un titre de 3 à 14 caractères est obligatoire."}
    validates :content,
    	presence: {message: "Un potin ne doit pas être vide."}
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"

	validates :content,
		presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggers
	has_many :potins, through: :taggers

	validates :title,
		presence: true
end

app/models/tagger.rb
class Tagger < ApplicationRecord
	belongs_to :potin
        belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :potins
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
        has_many :comments
	has_many :likes
	has_secure_password

	validates :first_name,
    	presence: true
    validates :last_name,
    	presence: true
    validates :age,
	    presence: true,
	    numericality: { greater_than: 0 }
  	validates :description,
	    presence: true,
	    length: { minimum: 10 }   
  	validates :email,
	    presence: true,
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Renseignez une adresse email valide." }

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  before_action :connected_user, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

 def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    id = current_user.id
    @comment = Comment.new(content: params[:content], user_id: id, potin_id: params[:gossip_id])
    @id = @comment.potin_id
    if @comment.save
      flash[:success] = "Votre commentaire a bien été enregistré!"
      redirect_to gossip_path(@id)
    else
      flash[:fail] = "Une erreur s'est produite!!"
      render 'new'
    end
      
    
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition   
  end

  def update
    @comment = Comment.find(params[:id])
    @id = @comment.potin_id
    @comment = @comment.update(content: params[:content])
    flash[:update] = "Le commentaire a bien été modifié"
    redirect_to gossip_path(@id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @id = @comment.potin_id
    @comment.destroy
    flash[:destroy] = "Le commentaire a bien été supprimé"
    redirect_to gossip_path(@id)
  end

  private

  def connected_user
    if session[:user_id].nil?
      flash[:loggin_needed] = "Please log in."
      redirect_to root_path
    end
  end

  def authenticate_user
    if current_user.id != Comment.find(params[:id]).user_id
      flash[:bad_user] = "Please log in."
      redirect_to root_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	like = Like.new(user_id: current_user.id, potin_id: params[:format])
  	like.save
  	flash[:like] = "Liked"
  	redirect_to root_path
  end

  def destroy
  	@like = Like.find_by(user_id: current_user.id, potin_id: params[:id])
  	@like.destroy
  	flash[:unlike] = "Unliked"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	# Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
	end

	def show
	# Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
		@user = User.find(params[:id])
	end

	def new
		@city = City.all
	end

	def create
	# Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
	# pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
	# Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)

		if params[:city] == "Sélectionner votre ville"
			flash[:fail] = "Une erreur s'est produite!!"
			redirect_to new_user_path
		else
			@user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: City.all.find_by(name: params[:city]).id, password: params[:password])

			if params[:password] == params[:repeated_password]
				if @user.save
			      flash[:inscription] = "Vous êtes enregistré"
			      log_in(@user)
			      flash[:login] = 'Login'
			      redirect_to root_path
			    else
			      flash[:fail] = "Une erreur s'est produite!!"
			      redirect_to new_user_path
			    end
			else
				flash[:fail_password] = "Ce n'est pas les mêmes mots de passes"
			    redirect_to new_user_path
			end
		end

	end

	def edit
	# Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
	end

	def update
	# Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
	# pour info, le contenu de ce formulaire sera accessible dans le hash params
	# Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
	end

	def destroy
	# Méthode qui récupère le potin concerné et le détruit en base
	# Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  
  def like?(potin)
    if Like.find_by(user_id: current_user.id, potin_id: potin.id).nil?
      return false
    else 
      return true
      id = like.id
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<% @comment = Comment.find(params[:id]) %>

<div class="contener text-center">
  </br></br>
  <h2>Vous êtes sur la page d'édition du commentaire du potin "<%= @comment.potin.title %>"</h2></br>
  <h4>Ce commentaire a été écrit par <%= @comment.user.first_name %> <%= @comment.user.last_name %>, le <%= @comment.created_at.strftime("%d/%m/%Y") %></h4></br>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail] %> 
    <div class="alert alert-danger" role="alert">
      Une erreur s'est produite!
    </div>
  <% end %>
</div>
   

  <%= form_tag  gossip_comment_path, method: "put" do %> 

    <div class="contener">

      <div class="form-group">
        <textarea type="text" name="content"  placeholder="Ici, le potin du potin" class="form-control" rows="4"><%= @comment.content %></textarea>
      </div>   

      <div class="d-flex justify-content-center">
        <div class="form-group row">
        <div class="col-sm-10">
            <input type="submit" value="Modifier" class="btn btn-primary"/>
        </div>
      </div>
    </div>

  <% end %>


    <%= form_tag gossip_comment_path(@comment.id), method: "delete" do %>
      <input type="submit" value="Supprimer" class="btn btn-danger"/>
    <% end %>

  </div>
</div>

app/views/comments/new.html.erb
<div class="contener text-center">
</br></br>
  <h2>Ici, on potine sur les potins !</h>
  </br>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail] %> 
    <div class="alert alert-danger" role="alert">
      Une erreur s'est produite!
    </div>
  <% end %>
</div>
   
<%= form_tag  gossip_comments_path do %> 

  <div class="contener">
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Contenu</label>
      <textarea type="text" name="content"  placeholder="Ici, le potin du potin" class="form-control" rows="4"></textarea>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Ajouter le potin" class="btn btn-primary"/>
    </div>
  </div>


<% end %>