config/routes.rb
Rails.application.routes.draw do

	root to: 'gossips#index'
	get 'static_pages/team', to: 'static_pages#team', as: 'team'
	get 'static_pages/contact', to: 'static_pages#contact', as: 'contact'
	get 'static_pages/:first_name', to: 'static_pages#welcome', as: 'secret_page'

	resources :gossips do
		resources :comments
	end
	resources :users
	resources :cities, only: [:show]
	resources :sessions, only: [:new, :create, :destroy]
	resources :likes, only: [:create, :destroy]

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :connected_user, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    params[:potins] = Potin.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Potin.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    id = current_user.id
    @gossip = Potin.new(title: params[:title], content: params[:content], user_id: id)

    if @gossip.save
      flash[:success] = "Votre potin a bien été enregistré!"
      redirect_to root_path
    else
      flash[:fail] = "Une erreur s'est produite!!"
      render 'new'
    end

  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Potin.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Potin.find(params[:id])
    
    if @gossip.update(title: params[:title], content: params[:content])
      flash[:success] = "Votre potin a bien été mis à jour!"
      redirect_to root_path
    else
      flash[:fail] = "Une erreur s'est produite!!"
      render edit
    end

  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Potin.find(params[:id])
    @gossip.destroy
    flash[:destroy] = "Le potin a bien été supprimé"
    redirect_to root_path
  end

  private

  def connected_user
    if session[:user_id].nil?
      flash[:loggin_needed] = "Please log in."
      redirect_to root_path
    end
  end

  def authenticate_user
    if current_user.id != Potin.find(params[:id]).user_id
      flash[:bad_user] = "Please log in."
      redirect_to root_path
    end
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<div class="contener text-center">
  </br></br>
  <h1>Vous êtes sur la page d'édition du potin nommé "<%= @gossip.title %>".</h1>
  </br>


  </br></br>
  <h2>Son auteur, <%= @gossip.user.first_name %> <%= @gossip.user.last_name %>, l'a enregistré le <%= @gossip.created_at.strftime("%d/%m/%Y") %>.</h2>
  <% if @gossip.created_at  != @gossip.updated_at %>
      <h4>
        <%= @gossip.updated_at.strftime("Dernière mise à jour le %d/%m/%Y") %> <%= @gossip.updated_at.strftime("à %H:%M")  %>
      </h4>
    <% end %>    
  </br>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail] %> 
    <div class="alert alert-danger" role="alert">
      Une erreur s'est produite!
    </div>
  <% end %>
</div>

<% if !@gossip.nil? && @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à mettre à jour le potin pour les raisons suivantes :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
   
<%= form_tag gossip_path, method: "put" do %>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Titre</label>
    <input type="text" name="title"  placeholder= <%= @gossip.title %> required class="form-control" rows="1"/>
  </div>      

  <div class="contener text-left">
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Contenu</label>
      <textarea type="text" name="content" class="form-control" rows="4" >
        <%= @gossip.content %>
      </textarea>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Mettre à jour" class="btn btn-primary"/>
    </div>
  </div>

<% end %>

app/views/gossips/index.html.erb
</br></br>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:unlike] %> 
    <div class="alert alert-success" role="alert">
      Vous avez supprimé votre like!
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:like] %> 
    <div class="alert alert-success" role="alert">
      Vous avez mis un like!
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:disconnected] %> 
    <div class="alert alert-danger" role="alert">
      Vous vous êtes bien déconnecté.</br>
      Merci de votre visite.</br>
      A bientôt.
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:loggin_needed] %> 
    <div class="alert alert-danger" role="alert">
      Vous devez être connecté pour commenter.</br>
      Si vous n'êtes pas encore membre, inscrivez-vous.
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:success] %> 
    <div class="alert alert-success" role="alert">
      Votre potin a bien été enregistré
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:destroy] %> 
    <div class="alert alert-danger" role="alert">
      Le potin a bien été supprimé
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:bad_user] %> 
    <div class="alert alert-danger" role="alert">
      Quand même...</br>
      Vous ne pouvez pas faire ça aux créations des autres.
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:inscription] %> 
    <div class="alert alert-success" role="alert">
      Vous êtes à présent membre de TGP
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:login] %> 
    <div class="alert alert-success" role="alert">
      <%= current_user.first_name %>, vous êtes maintenant logged
    </div>
  <% end %>
</div>

</br></br>
<div class='container text-center'>
  <h1 class="display-4">Bienvenue dans le monde des potins</h1>
</div></br></br>

<div class='container text-center'>
  <h1 class="display-6">Vous voulez créer un potin maintenant?</h1>
  <a class="btn btn-outline-primary" href="<%= new_gossip_path %>" >Potiner</a>
</div></br></br>

<div class='container'>
  <div class='card-deck'>
    <div class="row">
        <% params[:potins].each do |potin| %> 
          <div class="card border-primary mb-3" style="min-width: 20rem;">
            <div class="card-body">
                <h5 class="card-title"><%= potin.title %></h5>
                <p class="card-text">Un potin de <%= potin.user.first_name %>.</br>
                  
                <span class="badge badge-pill badge-primary">Likes: <%= potin.likes.count %></span></br>
                
                <% unless session[:user_id].nil? %>
                    <% if !like?(potin) %>
                        <%= link_to "Like?", likes_path(potin.id), method: :post %>
                      <% else %>
                        <%= link_to "Dislike?", like_path(potin.id), method: :delete %>
                    <% end %>                      
                <% end %></br></br>

                <%= link_to 'Clique pour en savoir plus.', gossip_path(@id = potin.id) %>

            </div>
            <div class="card-footer">
              <small class="text-muted"><%= potin.created_at.strftime("Créé le %d/%m/%Y") %>.</small>
            </div>    
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/gossips/new.html.erb
<div class="contener text-center">
</br></br>
  <h1 class="display-5">On veut tout savoir !</h1>
  </br>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail] %> 
    <div class="alert alert-danger" role="alert">
      Une erreur s'est produite!
    </div>
  <% end %>
</div>

<% if !@gossip.nil? && @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
   
<%= form_tag "/gossips", method: "post" do %>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Titre</label>
    <input type="text" name="title"  placeholder="Titre" required class="form-control" rows="1"/>
  </div>      

  <div class="contener">
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Contenu</label>
      <textarea type="text" name="content"  placeholder="Potin" class="form-control" rows="4"></textarea>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <input type="submit" value="Ajouter le potin" class="btn btn-primary"/>
    </div>
  </div>


<% end %>

app/views/gossips/show.html.erb
<div class="contener text-center" style="margin: 10px">
  <% if flash[:success] %> 
    <div class="alert alert-success" role="alert">
      Votre commentaire a bien été enregistré
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:update] %> 
    <div class="alert alert-success" role="alert">
      Votre commentaire a bien été modifié
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:destroy] %> 
    <div class="alert alert-danger" role="alert">
      Votre commentaire a bien été supprimé
    </div>
  <% end %>
</div>


</br></br>
<div class='container text-center'>
  <h1 class="display-5">Vous êtes sur la page particulière du potin nommé "<%= @gossip.title %>"</h1></br></br>

  <ul>Un potin de <%= @gossip.user.first_name %> <%= @gossip.user.last_name %>, de la ville de <%= link_to @gossip.user.city.name, city_path(@id = @gossip.user.city.id) %>:</br>


    <li><%= @gossip.created_at.strftime("Créé le %d/%m/%Y") %> <%= @gossip.created_at.strftime("à %H:%M")  %></li>
    <% if @gossip.created_at  != @gossip.updated_at %>
      <li>
        <%= @gossip.updated_at.strftime("Mis à jour le %d/%m/%Y") %> <%= @gossip.updated_at.strftime("à %H:%M")  %>
      </li>
    <% end %>    
  </ul>
</div></br></br>

<div class='container'>
    <div class="card border-primary mb-3" style="min-width: 20rem;">
      <div class="card-body text-center">
          <h5 class="card-title"><%= @gossip.title %></h5>
          <p class="card-text"><%= @gossip.content %></p>
          <span class="badge badge-pill badge-primary">Likes: <%= @gossip.likes.count %></span></br>

          <% unless session[:user_id].nil? %>
            <% if !like?(@gossip) %>
                <%= link_to "Like?", likes_path(@gossip.id), method: :post %>
              <% else %>
                <%= link_to "Dislike?", like_path(@gossip.id), method: :delete %>
            <% end %>                      
          <% end %></br></br>

          <%= link_to 'En découvrir plus sur cet auteur.', user_path(@id = @gossip.user.id) %>
      </div>
          <div class="card-footer">
            <small class="text-muted"><%= link_to 'Mettre à jour ce potin', edit_gossip_path(@id = @gossip.id) %>.</small>
          </div>   
    </div>
</div>

<div class="d-flex justify-content-center">
  <%= form_tag gossip_path, method: "delete" do %>
    <input type="submit" value="Supprimer ce potin" class="btn btn-outline-danger"/>
  <% end %>
</div>




<! commments here >
<% comments = Comment.where(potin_id: @gossip.id) %>

<div class='container'>
  <h5 class="text-center">SECTION COMMENTAIRES</h5></br>

  <div class="text-center">
    <button type="button" class="btn btn-outline-primary"><%= link_to 'Commenter', new_gossip_comment_path(@gossip.id) %></button>
  </div></br>

   <div class="d-flex justify-content-center"> 
    <div class='card-deck'>
      <div class="row">
          <% comments.each do |comment| %> 
            <div class="card border-primary mb-3" style="min-width: 20rem;">
              <div class="card-body">
                  <h5 class="card-title">Par <%= comment.user.first_name %> <%= comment.user.last_name %>:</h5>
                  <p class="card-text"><%= comment.content %></p>                                
              </div>
              <div class="card-footer">
                <small class="text-muted"><%= comment.created_at.strftime("Créé le %d/%m/%Y") %>.</small></br>
                <small class="sticky-bottom"> <%= link_to 'Modifier', edit_gossip_comment_path(@gossip.id, comment.id) %></small>
              </div>    
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>