config/routes.rb
Rails.application.routes.draw do

	root to: 'gossips#index'
	get 'static_pages/team', to: 'static_pages#team', as: 'team'
	get 'static_pages/contact', to: 'static_pages#contact', as: 'contact'
	get 'static_pages/:first_name', to: 'static_pages#welcome', as: 'secret_page'

	resources :gossips do
		resources :comments
	end
	resources :users
	resources :cities, only: [:show]
	resources :sessions, only: [:new, :create, :destroy]
	resources :likes, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users

	validates :name,
    	presence: true
    validates :zip_code,
    	presence: true,
    	uniqueness: true,
    	format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Reneignez un code postal valide." }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :potin
  belongs_to :user
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
     belongs_to :potin
     belongs_to :user
end

app/models/potin.rb
class Potin < ApplicationRecord
	belongs_to :user
        has_many :taggers
        has_many :tags, through: :taggers
        has_many :comments
	has_many :likes

    validates :title,
    	presence: true,
    	length: { in: 3..14, message: "Un titre de 3 à 14 caractères est obligatoire."}
    validates :content,
    	presence: {message: "Un potin ne doit pas être vide."}
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"

	validates :content,
		presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggers
	has_many :potins, through: :taggers

	validates :title,
		presence: true
end

app/models/tagger.rb
class Tagger < ApplicationRecord
	belongs_to :potin
        belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :potins
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
        has_many :comments
	has_many :likes
	has_secure_password

	validates :first_name,
    	presence: true
    validates :last_name,
    	presence: true
    validates :age,
	    presence: true,
	    numericality: { greater_than: 0 }
  	validates :description,
	    presence: true,
	    length: { minimum: 10 }   
  	validates :email,
	    presence: true,
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Renseignez une adresse email valide." }

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	like = Like.new(user_id: current_user.id, potin_id: params[:format])
  	like.save
  	flash[:like] = "Liked"
  	redirect_to root_path
  end

  def destroy
  	@like = Like.find_by(user_id: current_user.id, potin_id: params[:id])
  	@like.destroy
  	flash[:unlike] = "Unliked"
  	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  
  def like?(potin)
    if Like.find_by(user_id: current_user.id, potin_id: potin.id).nil?
      return false
    else 
      return true
      id = like.id
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Lien Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
       
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <%= link_to 'The Gossip Project', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTog" aria-controls="navbarTog" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTog">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Team', team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: "nav-link" %>
          </li>
        </ul>

        <div>     

          <% if session[:user_id].nil? %>
            <a class="btn btn-primary" href="<%= new_user_path %>" >Inscription</a>         
            <a class="btn btn-secondary" href="<%= new_session_path %>" >Login</a>          
          <% end %>

          <% unless session[:user_id].nil? %>
              <%= form_tag session_path(session[:user_id]), method: "delete" do %>
              <input type="submit" value="Logout" class="btn btn-secondary"/>
              <% end %>             
          <% end %>

        </div> 


      </div>
    </nav>


    <%= yield %>

  </body>
</html>